env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:vue/essential
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
  - 'plugin:prettier/recommended'
rules: {}
